#!/usr/bin/env python3
"""Reproduce every quantitative result in the APDM paper.

Runs each experiment in src/ in order and prints a PASS/FAIL summary.
Run from the repo root:  python3 reproduce.py

External requirements (beyond numpy/scipy/matplotlib):
  * the cosmology experiments marked [SEDE] import the SEDE background/growth
    model, vendored in src/sede/ and resolved relative to each script;
  * the data-driven falsifiers marked [data] re-fetch public catalogues
    (VizieR / SDSS SAS / SPARC) on first run and need network access.
Experiments with an unmet requirement will report FAIL; the self-contained
ones run with only the packages in requirements.txt.

make_apdm_figures.py is run here in --no-save mode: it prints the §4 forecast
numbers (density/rate dispersion offsets and separability vs N, DESI-anchored, as
in the paper) without writing the figure files. The figures themselves are
regenerated by running make_apdm_figures.py without --no-save.
"""
import subprocess, sys, os, time

ROOT = os.path.dirname(os.path.abspath(__file__))
EXP = os.path.join(ROOT, "src")

# (script, description). Grouped by the paper section each result supports.
STAGES = [
    # Core: derived parameter point and mechanism (§5–§7)
    ("compute_solidification.py",       "Derived parameter point; §5/§6/§7 numbers"),
    ("solve_emergent.py",               "G3 (healing-length artifact) + G1 (a_0(z) branch selection)"),
    ("e9_mechanism_bridge.py",          "E9: halo-integrated condensate fraction vs SEDE f_sat  [SEDE]"),
    ("e9_tightened.py",                 "E9 tightened: actual s_AH normalization + Delta scan  [SEDE]"),
    ("e1_lock_constant.py",             "E1: absolute DM-DE lock constant K = 1/(2pi sqrt(3 Omega_DE))"),

    # §3 E-1: the headline branch discrimination against MUSE-DARK III
    ("branch_discrimination_test.py",   "E-1 headline: density branch EXCLUDED +16.7sigma, rate branch +4.4sigma (Fig 1)"),

    # §3–§4: observability, forecast, falsifiers
    ("make_apdm_figures.py --no-save",  "§3–§4 DESI-anchored a_0(z) forecast: dispersion offsets + separability (Figs 1–2)"),
    ("run_smoking_gun_predictions.py",  "§6 three smoking-gun signature predictions  [data]"),
    ("run_screening_dwarf_test.py",     "§4/§6 field-vs-satellite dwarf screening falsifier  [data]"),

    # §5: superfluid (Berezhiani–Khoury) realization
    ("run_phonon_sound_speed.py",       "§5 BK phonon sound speed c_s(r) from the condensate EOS"),
    ("test_one_coupling_two_faces.py",  "§5 one-coupling-two-faces: emergent unification test  [SEDE]"),

    # Appendix B: dark-sector coupling — theorem, stability, consistency
    ("test_coarsegrain_landau.py",      "App B: coarse-grained near-tricritical Landau free energy"),
    ("test_landau_action_wpsi.py",      "App B: V(psi)=a psi^2 + c psi^6 action, w_psi(z)"),
    ("test_covariant_landau_stability.py","App B: covariant Landau stability gate (selects psi=+1, non-phantom)"),
    ("test_twofield_completion.py",     "App B: two-field completion — ghost-free and non-phantom  [SEDE]"),
    ("test_tricritical_attractor.py",   "App B: why the dark sector sits near-tricritical (b~0 attractor)"),
    ("test_relaxational_psi.py",        "App B: relaxational (not conservative) psi dynamics"),
    ("test_doom_instability.py",        "App B: interacting-DE 'doom' instability residual, closed  [SEDE]"),
    ("test_growth_perturbations.py",    "App B: growth / fsigma8(z) consistency of the completion  [SEDE]"),
    ("test_downstream_tasks.py",        "App B: §9 downstream numerical tasks  [SEDE]"),
]

def main():
    results = []
    for entry, desc in STAGES:
        script, *args = entry.split()          # entry may carry CLI args, e.g. "foo.py --no-save"
        path = os.path.join(EXP, script)
        print(f"\n{'='*72}\n[RUN] {entry}\n      {desc}\n{'='*72}")
        t0 = time.time()
        r = subprocess.run([sys.executable, path, *args], cwd=EXP)
        ok = r.returncode == 0
        results.append((script, ok, time.time() - t0))
    npass = sum(ok for _, ok, _ in results)
    print(f"\n{'='*72}\nSUMMARY  ({npass}/{len(results)} passed)\n{'='*72}")
    for script, ok, dt in results:
        print(f"  {'PASS' if ok else 'FAIL'}  {script:34s}  ({dt:5.1f}s)")
    sys.exit(0 if npass == len(results) else 1)

if __name__ == "__main__":
    main()
